### ISSUE TITLE
Vyhodiť O2TV

### ISSUE THREAD

**Issue by skyjet18** [archivczsk/archivczsk-doplnky#1]
O2TV už nie je udržiavané -> vyhodiť. Náhrada je "Sledovani O2TV"

**Comment by misanov** [comment]
Možná by stálo za to, udělat statistiku spouštění doplňků a podle toho usoudit jestli má smysl spravovat i další doplňky, které jsou zastaralé a nepoužívané.

**Comment by skyjet18** [comment]
Vymazané v commite https://github.com/archivczsk/archivczsk-doplnky/commit/777390cba34327c086a37265f877560a710f10d7
