### ISSUE TITLE
Nahravanie cez plugin Markiza

### ISSUE THREAD

**Issue by joetitan01** [archivczsk/archivczsk-doplnky#11]
Pri nahrávaní cez plugin Markiza, pri voľbe cez menu "Stiahnuť" uložený záznam neobsahuje audio stopu. Priame prehrávanie z archívu funguje správne.

**Comment by skyjet18** [comment]
Opravené vo ArchivCZSK verzia >=2.2.3. Nutné mať v systéme nainštalované ffmpeg inak sa použije gstreamer tak ako doteraz ktorý nepodporuje sťahovanie oddelených video a audio streamov (resp. neviem ako ho nastaviť aby to vedel).
