### ISSUE TITLE
Nefunguje Live vysielanie v Nova Plus

### ISSUE THREAD

**Issue by skyjet18** [archivczsk/archivczsk-doplnky#2]
Aktuálne na spustenie live vysielania je nutné najprv spustiť televízne noviny a potom rýchlo spustiť live vysielanie.

**Comment by skyjet18** [comment]
Vyskúšané opäť a s exteplayer3 funguje nie len pri spustení live TN vysielania ale stále. Testované na OpenPLi 8.1 a OpenATV 7.3. Nateraz zatváram ako problém na strane serverov novy.

**Comment by misanov** [comment]
Ano, zjištěno, že živé vysílání potřebuje nainstalovaný a vybraný exteplayer3, bez něj nefunguje.
