### ISSUE TITLE
Nefungujú vnorené titulky v SCC

### ISSUE THREAD

**Issue by vatlach** [archivczsk/archivczsk-doplnky#5]
SCC ma problem s vnorenymi titulkami.Nie je moznost ich vybrat.

**Comment by skyjet18** [comment]
So SCC a ani akýmkoľvek iným doplnkom nemajú vnorené titulky absolútne nič spoločné. Ich zobrazenie je vecou prehrávača a pluginu SubsSupport. Ak nefungujú, tak treba problém hľadať tam.
