### ISSUE TITLE
Archív CZ SK,nie premium

### ISSUE THREAD

**Issue by jurajpetko** [archivczsk/archivczsk-doplnky#6]
V stream cinema community neprehrá video.Po kliknutí na video ma ihneď vráti naspäť.
Verzia 1.5.0.

OpenPli 7,2,Vu Solo 2

**Comment by skyjet18** [comment]
Málo informácii. Prosím pridať logy z /tmp/archivczsk.log, popísať nastavenie systému (tzn. či je nainštalovaný plugin ServiceApp a ako je nastavený) a aký prehrávač je nastavený v nastaveniach SCC addonu.

**Comment by jurajpetko** [comment]
Ahoj,
  plugin ServiceApp je nainštalovaný
nastavený prehrávač exteplayer 3 aj  v plugine aj v SCC,prikladám foto a
log v prílohe

[image: image.jpeg]


Juraj


št 22. 9. 2022 o 8:02 skyjet18 ***@***.***> napísal(a):

**Comment by jurajpetko** [comment]
![nastavenie v service app 2 ](https://user-images.githubusercontent.com/46195138/191718775-96759e93-5425-48af-bb4b-47da60973fed.jpg)
![nastavenie v service app 1](https://user-images.githubusercontent.com/46195138/191718867-e7e5e0b0-847b-4f09-905b-36526ecf1e11.jpg)
![nastavenie v SCC](https://user-images.githubusercontent.com/46195138/191718893-2fdc8d53-9426-4569-b6e6-1860241b439a.jpg)
[archivCZSK.log](https://github.com/archivczsk/archivczsk-doplnky/files/9624585/archivCZSK.log)

**Comment by skyjet18** [comment]
V tom logu je len start archivCZSK. Potrebujem log v ktorom je vidiet spustenie samotneho filmu. Len pre istotu: meno/heslo pre webshare v nastaveniach mas zadane? Lebo podla screenshotu ich zadane nemas. Bez nich to samozrejme nepojde.

**Comment by jurajpetko** [comment]
Heslo som nemal,nemal som registraciu na webshare,predtym mi to slo aj bez mena a hesla.
Teraz som sa zaregistroval,ulozil prihlasovacie udaje,ale aj tak to nejde.
[archivCZSK.log](https://github.com/archivczsk/archivczsk-doplnky/files/9624974/archivCZSK.log)

**Comment by skyjet18** [comment]
Podľa logu je zo strany SCC aj archivCZSK všetko v poriadku - bol nájdený odkaz na stream a ten bol predaný prehrávaču. Odkaz na stream je funkčný, takže problém je niekde v prehrávači v systéme. Prosím over si, že máš zadané správne meno/heslo a že ti ukazuje VIP days na kladný počet dní. Ďalej navrhujem zmeniť nastavenia prehrávača v doplnku na Default a rovnako aj v nastaveniach ServiceApp vypnúť Enigma2 playback system (hneď prvá voľba). Potom reštart prijímača. Tým sa ako default prehrávač použije vstavaný, ktorý by v tomto prípade mohol fungovať lepšie. Bug report zatváram, keďže sa nejedná o chybu v doplnku. Ak ti to ani potom nepôjde, tak hľadaj podporu napr. na ab-fóre kde takýto problém riešili už viacerí.
